name: Deploy app

on:
  workflow_dispatch:
  push:
    branches: 
      - master

jobs:
  publish-and-deploy:
    runs-on: ubuntu-latest

    steps:    
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: "master"
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x    
      env: 
        DOTNET_CLI_TELEMETRY_OPTOUT : 1
    - name: Install dependencies
      run: dotnet restore
    - name: Publish
      run: dotnet publish HiraganeoApp --configuration Release -f netcoreapp3.1 -r linux-x64 -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained true -o ./publish
    - name: Copy files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        source: "./publish/*"
        target: "sites/hiraganeo.axonited.net/new_release"
        strip_components: 1
    - name: Prepare release & restart services
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          sudo systemctl stop hiraganeo
          cp -rf ~/sites/hiraganeo.axonited.net/new_release/* ~/sites/hiraganeo.axonited.net
          rm -Rf ~/sites/hiraganeo.axonited.net/new_release
          sudo systemctl start hiraganeo
