name: deploy

on:
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: deploy
      env:
        SSH_HOST: axonited.net
        SSH_USER: ${{ secrets.USER }}
        SSH_PASS: ${{ secrets.PASSWORD }}
      run: |
        echo "starting"
        ls -la
        git checkout $GITHUB_SHA        
        ls -la
        echo "finished"       
