name: deploy

on:
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        ref: "master"
    - name: pack
      run: |
        cd $GITHUB_WORKSPACE
        ls -la
        tar -czvf hiraganeo.tar.gz .
        ls -la
    - name: upload
      uses: actions/upload-artifact@v2
      with:
        name: "hiraganeo"
        path: hiraganeo.tar.gz
    - name: deploy
      env:
        SSH_HOST: axonited.net
        SSH_USER: ${{ secrets.USER }}
        SSH_PASS: ${{ secrets.PASSWORD }}
      run: |
        echo "starting"
        cd $GITHUB_WORKSPACE
        ls -la
        echo "server copy here"
        echo "finished"       
