name: deploy

on:
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: deploy
      env:
        SSH_HOST: axonited.net
        SSH_USER: ${{ secrets.USER }}
        SSH_PASS: ${{ secrets.PASSWORD }}
      run: |
        cd /tmp
        mkdir hiraganeo
        cd hiraganeo
        git checkout $GITHUB_SHA .
        ls -la
        
